services:
  # 1. Database PostgreSQL 16 (Toi uu gioi han RAM 512MB)
  postgres_db:
    image: postgres:16-alpine
    container_name: app_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    mem_limit: 512m
    deploy:
      resources:
        limits:
          memory: 512M

  # 2. Backend NestJS 11 (Toi uu gioi han RAM 1024MB)
  backend_api:
    build:
      context: ./be
      dockerfile: Dockerfile
    container_name: app_backend
    restart: always
    command: sh -c "npx prisma db push && node dist/main"
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres_db:5432/${POSTGRES_DB}?schema=public
    depends_on:
      postgres_db:
        condition: service_healthy
    mem_limit: 1024m
    deploy:
      resources:
        limits:
          memory: 1024M

  # 3. Frontend React 19 + Vite 8 (Toi uu gioi han RAM 512MB)
  frontend_web:
    build:
      context: ./fe
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL}
    container_name: app_frontend
    restart: always
    ports:
      - '5173:80'
    depends_on:
      - backend_api
    mem_limit: 512m
    deploy:
      resources:
        limits:
          memory: 512M

volumes:
  pgdata: